name: cloakhat
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pytorch3d
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - ipykernel
  - pytorch3d
  - pytorch-cuda=11.8
  - pip
  - pip:
    - ultralytics
    - opencv-python-headless
    - matplotlib
    - tqdm
    - tensorboard
    - pyyaml
    - trimesh